---
application:
  name: "qv-test-v2"
  project: "qv-test-v2"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "my_mongo"
  version: "4.4"
routers:
- name: "main-qv-test-v2"
  routes:
  - application_name: "qv-test-v2"
    paths:
    - "/*"
